version: "3.3"

services:
  nginx:
    image: nginx_msantos
    container_name: nginx
    build: ./requirements/nginx
    volumes:
    -  '/requirements/nginx/default:/etc/nginx/conf.d/default.conf'
    ports:
    - "443:443"
    tty: true
    restart: always
  wordpress:
    image: wordpress_msantos
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
    -  '/data/wordpress:/usr/share'
    ports:
    - "9000:9000"
    tty: true
    restart: always
